name: Workflow Dotnet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar e executar teste
      uses: actions/checkout@v2
    - name: Instalar dependências
      run: npm install # Ou outro comando para instalar dependências
    - name: Executar teste
      run: npm test # Ou outro comando para executar os testes

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Verificar e fazer checkout do código
      uses: actions/checkout@v2
    - name: Construir artefatos
      run: npm run build # Ou comando para construir artefatos do seu projeto
    - name: Implantação no servidor
      uses: ad-m/github-push-action@master # Action pré-existente para fazer push de artefatos para um servidor
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: deploy
        force: true
