name: Workflow Dotnet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Execute every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        echo "Running tests..."
        # Add commands to run tests for your project

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build artifacts
      run: |
        echo "Building artifacts..."
        # Add commands to build artifacts for your project
    - name: Display debug information
      run: |
        echo "GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}"
        echo "Git user: $(git config prinakayama)"
        echo "Git email: $(git config priscila.nakayama@yahoo.com)"
    - name: Deploy to GitHub Pages
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        branch: deploy
        force: true
