name: Workflow Dotnet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar e executar teste
      uses: actions/checkout@v2 # Action pré-existente do GitHub para clonar o repositório
    - name: Instalar dependências
      run: npm install # Ou outro comando para instalar dependências
    - name: Executar teste
      run: npm test # Ou outro comando para executar os testes

  deploy:
    runs-on: ubuntu-latest
    needs: build # Garante que a job de deploy só é executada após a conclusão da job de build

    steps:
    - name: Verificar e fazer checkout do código
      uses: actions/checkout@v2
    - name: Executar script de implantação
      run: ./deploy.sh # Script personalizado para implantação
