name: Workflow Dotnet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar e executar teste
      uses: actions/checkout@v2
    - name: Executar teste
      run: |
        # Comandos para executar os testes do seu projeto

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Verificar e fazer checkout do código
      uses: actions/checkout@v2
    - name: Construir artefatos
      run: |
        # Comandos para construir os artefatos do seu projeto
    - name: Implantação no servidor
      uses: ad-m/github-push-action@master
      with:
        github_token: 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
        branch: deploy
        force: true
